// Generated by CoffeeScript 1.6.3
/*
  あかんやつ
*/

var fizzbuzz1, fizzbuzz2, fizzbuzz3, fizzbuzz4, fizzbuzz5, fizzbuzz6, fizzbuzz7, fizzbuzz8;

fizzbuzz1 = function(l) {
  var i, p, _i, _results;
  p = $('#fb1 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 15 === 0) {
      p.append('fizzbuzz');
    } else {
      if (i % 3 === 0) {
        p.append('fizz');
      } else if (i % 5 === 0) {
        p.append('buzz');
      } else {
        p.append(i);
      }
    }
    _results.push(p.append('<br>'));
  }
  return _results;
};

/*
  以前Javaで書いたやつと同じ流れで書くと…
*/


fizzbuzz2 = function(l) {
  var i, p, _i, _results;
  p = $('#fb2 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 3 === 0) {
      p.append('fizz');
    }
    if (i % 5 === 0) {
      p.append('buzz');
    } else if (i % 3 !== 0) {
      p.append(i);
    }
    _results.push(p.append('<br>'));
  }
  return _results;
};

/*
  Coffeeぽく書くと…
*/


fizzbuzz3 = function(l) {
  var a, i, p, _i, _results;
  p = $('#fb3 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    a = [];
    if (i % 3 === 0) {
      a.push('fizz');
    }
    if (i % 5 === 0) {
      a.push('buzz');
    }
    if (a.length === 0) {
      a.push(i);
    }
    a.push('<br>');
    _results.push(p.append(a.join('')));
  }
  return _results;
};

/*
  appendは一回
*/


fizzbuzz4 = function(l) {
  var a, i, _i;
  a = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 3 < 1) {
      a.push('fizz');
    }
    if (i % 5 < 1) {
      a.push('buzz');
    }
    if (i % 3 > 0 && i % 5 > 0) {
      a.push(i);
    }
    a.push('<br>');
  }
  return $('#fb4 p').append(a.join(''));
};

/*
  .map()で手を抜いてみる
*/


fizzbuzz5 = function(l) {
  var a, _i, _results;
  a = (function() {
    _results = [];
    for (var _i = 1; 1 <= l ? _i <= l : _i >= l; 1 <= l ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  return $('#fb5 p').append(a.map(function(i) {
    _i = i % 3 < 1 ? 'fizz' : '';
    return _i += i % 5 < 1 ? 'buzz' : i % 3 < 1 ? '' : i;
  }).join('<br>'));
};

/*
  例えばswitch
*/


fizzbuzz6 = function(l) {
  var a, i, _i;
  a = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    switch (i % 15) {
      case 0:
        a.push('fizzbuzz');
        break;
      case 3 || 6 || 9:
        a.push('fizz');
        break;
      case 5 || 10:
        a.push('buzz');
        break;
      default:
        a.push(i);
    }
  }
  return $('#fb6 p').append(a.join('<br>'));
};

/*
  原始的だけど、処理的には最短のはず…
*/


fizzbuzz7 = function(l) {
  var a, _i, _results;
  a = (function() {
    _results = [];
    for (var _i = 1; 1 <= l ? _i <= l : _i >= l; 1 <= l ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  return $('#fb7 p').append(a.map(function(i) {
    if (i % 3 < 1) {
      if (i % 5 < 1) {
        return 'fizzbuzz';
      } else {
        return 'fizz';
      }
    } else if (i % 5 < 1) {
      return 'buzz';
    }
    return i;
  }).join('<br>'));
};

/*
  お約束の配列使用
*/


fizzbuzz8 = function(l) {
  var a, b, _i, _results;
  a = (function() {
    _results = [];
    for (var _i = 1; 1 <= l ? _i <= l : _i >= l; 1 <= l ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  b = ['fizzbuzz', null, null, 'fizz', null, 'buzz', 'fizz', null, null, 'fizz', 'buzz', null, 'fizz', null, null];
  return $('#fb8 p').append(a.map(function(i) {
    var _ref;
    return _i = (_ref = b[i % 15]) != null ? _ref : i;
  }).join('<br>'));
};

$(function() {
  var limit;
  limit = 1000;
  fizzbuzz1(limit);
  fizzbuzz2(limit);
  fizzbuzz3(limit);
  fizzbuzz4(limit);
  fizzbuzz5(limit);
  fizzbuzz6(limit);
  fizzbuzz7(limit);
  return fizzbuzz8(limit);
});
