// Generated by CoffeeScript 1.6.3
/*
  あかんやつ
*/

var fizzbuzz1, fizzbuzz2, fizzbuzz3, fizzbuzz4, fizzbuzz5;

fizzbuzz1 = function(l) {
  var i, p, _i, _results;
  p = $('#fb1 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 15 === 0) {
      p.append('fizzbuzz');
    } else {
      if (i % 3 === 0) {
        p.append('fizz');
      } else if (i % 5 === 0) {
        p.append('buzz');
      } else {
        p.append(i);
      }
    }
    _results.push(p.append('<br>'));
  }
  return _results;
};

/*
  以前Javaで書いたやつと同じ流れで書くと…
*/


fizzbuzz2 = function(l) {
  var i, p, _i, _results;
  p = $('#fb2 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 3 === 0) {
      p.append('fizz');
    }
    if (i % 5 === 0) {
      p.append('buzz');
    } else if (i % 3 !== 0) {
      p.append(i);
    }
    _results.push(p.append('<br>'));
  }
  return _results;
};

/*
  Coffeeぽく書くと…
*/


fizzbuzz3 = function(l) {
  var a, i, p, _i, _results;
  p = $('#fb3 p');
  _results = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    a = [];
    if (i % 3 === 0) {
      a.push('fizz');
    }
    if (i % 5 === 0) {
      a.push('buzz');
    }
    if (a.length === 0) {
      a.push(i);
    }
    a.push('<br>');
    _results.push(p.append(a.join('')));
  }
  return _results;
};

/*
  appendは一回
*/


fizzbuzz4 = function(l) {
  var a, i, _i;
  a = [];
  for (i = _i = 1; 1 <= l ? _i <= l : _i >= l; i = 1 <= l ? ++_i : --_i) {
    if (i % 3 < 1) {
      a.push('fizz');
    }
    if (i % 5 < 1) {
      a.push('buzz');
    }
    if (i % 3 > 0 && i % 5 > 0) {
      a.push(i);
    }
    a.push('<br>');
  }
  return $('#fb4 p').append(a.join(''));
};

/*
*/


fizzbuzz5 = function(l) {
  var a, _i, _results;
  a = (function() {
    _results = [];
    for (var _i = 1; 1 <= l ? _i <= l : _i >= l; 1 <= l ? _i++ : _i--){ _results.push(_i); }
    return _results;
  }).apply(this);
  return $('#fb4 p').append(a.map(function(i) {
    _i = i % 3 < 1 ? 'fizz' : '';
    return _i += i % 5 < 1 ? 'buzz' : i % 3 < 1 ? '' : i;
  }).join('<br>'));
};

$(function() {
  var limit;
  limit = 1000;
  fizzbuzz1(limit);
  fizzbuzz2(limit);
  fizzbuzz3(limit);
  fizzbuzz4(limit);
  return fizzbuzz5(limit);
});
